name: Build and upload artifact

on:
  push:
    branches: 
      - '0nee-main'

jobs:
  build_soapbox:
    name: build soapbox
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.9.0]
    steps:
      - name: get repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.after }}
      - name: set Node.js env
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ matrix.node-version }}-soapbox
      - name: Install packages
        run: test -d node_modules || yarn install --frozen-lockfile
      - name: Build project
        env:
          NODE_ENV: 'production'
        run: yarn build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: soapbox-build
          path: dist
